import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthButton from "./components/AuthButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body>
    <nav
        style={{
            padding: 16,
            borderBottom: "1px solid #ddd",
            display: "flex",
            gap: 16,
            alignItems: "center",
        }}
    >
        <a href="/">Home</a>
        <a href="/spots">NYC Spots</a>
        <a href="/profile">Profile</a>
        <a href="/members">Members</a>
        <span style={{ marginLeft: "auto" }}>
            <AuthButton />
        </span>
    </nav>
    {children}
    </body>
    </html>
  );
}
